"""
Prepare MkDocs source files for the personal knowledge-base wiki.

The AI-organized wiki is maintained at the repository root (`index.md`,
`concepts/`, `entities/`, `comparisons/`). MkDocs requires all served files to
live under `docs/`, so this script creates generated copies there before
`mkdocs serve` or `mkdocs build` runs.
"""

from __future__ import annotations

import re
import shutil
from pathlib import Path


ROOT = Path(__file__).resolve().parent
DOCS = ROOT / "docs"
MARKER = ".generated-by-prepare-wiki-docs"

ROOT_FILES = ["index.md", "log.md", "SCHEMA.md"]
WIKI_DIRS = ["concepts", "entities", "comparisons"]
WIKILINK_RE = re.compile(r"\[\[([^\]|#]+)(?:#([^\]|]+))?(?:\|([^\]]+))?\]\]")


def normalize_name(value: str) -> str:
    return value.strip().replace(" ", "-").lower()


def build_page_index() -> dict[str, Path]:
    index: dict[str, Path] = {}
    for dirname in WIKI_DIRS:
        source_dir = ROOT / dirname
        if not source_dir.exists():
            continue

        for path in source_dir.rglob("*.md"):
            relative = path.relative_to(ROOT).as_posix()
            keys = {
                path.stem,
                path.stem.lower(),
                normalize_name(path.stem),
                relative[:-3],
                relative[:-3].lower(),
            }
            for key in keys:
                index.setdefault(key, Path(relative))

    return index


def markdown_anchor(value: str) -> str:
    return value.strip().lower().replace(" ", "-")


def convert_wikilinks(text: str, output_path: Path, page_index: dict[str, Path]) -> str:
    def replace(match: re.Match[str]) -> str:
        target = match.group(1).strip()
        anchor = match.group(2)
        alias = match.group(3)
        label = (alias or target).strip()

        if target.startswith(("http://", "https://")):
            href = target
        else:
            page = (
                page_index.get(target)
                or page_index.get(target.lower())
                or page_index.get(normalize_name(target))
            )
            if page is None:
                return label

            source_dir = output_path.parent
            target_path = DOCS / page
            href = Path(
                re.sub(
                    r"\\",
                    "/",
                    str(target_path.relative_to(source_dir) if target_path.is_relative_to(source_dir) else Path("..") / target_path.relative_to(DOCS)),
                )
            ).as_posix()

        if anchor:
            href = f"{href}#{markdown_anchor(anchor)}"

        return f"[{label}]({href})"

    return WIKILINK_RE.sub(replace, text)


def ensure_generated_dir(path: Path) -> None:
    if path.exists() and not (path / MARKER).exists():
        raise RuntimeError(f"Refusing to overwrite non-generated directory: {path}")

    if path.exists():
        shutil.rmtree(path)

    path.mkdir(parents=True)
    (path / MARKER).write_text("Generated by prepare_wiki_docs.py\n", encoding="utf-8")


def write_markdown(source: Path, target: Path, page_index: dict[str, Path]) -> None:
    target.parent.mkdir(parents=True, exist_ok=True)
    text = source.read_text(encoding="utf-8")
    text = convert_wikilinks(text, target, page_index)
    target.write_text(text, encoding="utf-8")


def sync_file(source_name: str, page_index: dict[str, Path]) -> None:
    source = ROOT / source_name
    if source.exists():
        write_markdown(source, DOCS / source_name, page_index)


def sync_dir(dirname: str, page_index: dict[str, Path]) -> None:
    source_dir = ROOT / dirname
    target_dir = DOCS / dirname
    if not source_dir.exists():
        return

    ensure_generated_dir(target_dir)
    for source in source_dir.rglob("*"):
        relative = source.relative_to(source_dir)
        target = target_dir / relative
        if source.is_dir():
            target.mkdir(parents=True, exist_ok=True)
        elif source.suffix.lower() == ".md":
            write_markdown(source, target, page_index)
        else:
            target.parent.mkdir(parents=True, exist_ok=True)
            shutil.copy2(source, target)


def main() -> None:
    DOCS.mkdir(exist_ok=True)
    page_index = build_page_index()

    for source_name in ROOT_FILES:
        sync_file(source_name, page_index)

    for dirname in WIKI_DIRS:
        sync_dir(dirname, page_index)

    print("Wiki docs prepared under docs/.")


if __name__ == "__main__":
    main()
